import {
  AppstoreOutlined,
  ApartmentOutlined,
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  BellOutlined,
  BookOutlined,
  CalendarOutlined,
  CarryOutOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  CloudOutlined,
  ClusterOutlined,
  ContactsOutlined,
  ControlOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DollarOutlined,
  ExportOutlined,
  FileDoneOutlined,
  FileTextOutlined,
  FolderOutlined,
  GiftOutlined,
  GlobalOutlined,
  HomeOutlined,
  IdcardOutlined,
  KeyOutlined,
  LineChartOutlined,
  LockOutlined,
  MailOutlined,
  MenuOutlined,
  MinusCircleOutlined,
  NotificationOutlined,
  PieChartOutlined,
  ProfileOutlined,
  ProjectOutlined,
  SafetyOutlined,
  ScheduleOutlined,
  SettingOutlined,
  ShopOutlined,
  SolutionOutlined,
  TeamOutlined,
  ToolOutlined,
  TrophyOutlined,
  UserOutlined,
  UsergroupAddOutlined,
  WalletOutlined,
} from "@ant-design/icons";
import type { ComponentType } from "react";

/** Icons usable in the DB-driven menu, looked up by the name stored in Menus.IconName. */
export const MENU_ICONS: Record<string, ComponentType> = {
  AppstoreOutlined,
  ApartmentOutlined,
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  BellOutlined,
  BookOutlined,
  CalendarOutlined,
  CarryOutOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  CloudOutlined,
  ClusterOutlined,
  ContactsOutlined,
  ControlOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DollarOutlined,
  ExportOutlined,
  FileDoneOutlined,
  FileTextOutlined,
  FolderOutlined,
  GiftOutlined,
  GlobalOutlined,
  HomeOutlined,
  IdcardOutlined,
  KeyOutlined,
  LineChartOutlined,
  LockOutlined,
  MailOutlined,
  MenuOutlined,
  NotificationOutlined,
  PieChartOutlined,
  ProfileOutlined,
  ProjectOutlined,
  SafetyOutlined,
  ScheduleOutlined,
  SettingOutlined,
  ShopOutlined,
  SolutionOutlined,
  TeamOutlined,
  ToolOutlined,
  TrophyOutlined,
  UserOutlined,
  UsergroupAddOutlined,
  WalletOutlined,
};

export const MENU_ICON_NAMES = Object.keys(MENU_ICONS);

export const isKnownMenuIcon = (name?: string | null): boolean => !!name && name in MENU_ICONS;

/** Renders the named icon, falling back to a neutral placeholder for unknown names. */
export const renderMenuIcon = (name?: string | null) => {
  if (!name) return null;
  const Icon = MENU_ICONS[name] ?? MinusCircleOutlined;
  return <Icon />;
};
