


const URL = {
    Login: "/login",
    DashboardAdmin: "/dashboard/admin",
    DashboardManage: "/dashboard/manage",
    DashboardHR: "/dashboard/hr",
    DashboardStaff: "/dashboard/staff",
    DashboardPurchase: "/dashboard/purchase",
    DashboardSale: "/dashboard/sale",
    ManageUser: "/admin/manage-user",
    ManageRole: "/admin/manage-role",
    ManageCategory: "/admin/manage-category",
    ManageProduct: "/admin/manage-product",
    ManageTask: "/manage-task",
    ManagePayrollPolicy: "/admin/manage-payroll-policy",
    ManageEmployee: "/hr/manage-employee",
    EmployeeDetail: "/hr/manage-employee/:id",
    ManageDepartment: "/hr/manage-department",
    DepartmentDetail: "/hr/manage-department/:id",
    ManagePosition: "/hr/manage-position",
    PositionDetail: "/hr/manage-position/:id",
    MyAttendance: "/attendance/my",
    ManageAttendance: "/attendance/manage",
    ManageHRProcedure: "/hr/manage-procedure",
    ManageShift: "/hr/manage-shift",
    ManageShiftAssignment: "/hr/manage-shift-assignment",
    MyLeaveRequest: "/leave/my",
    ManageLeaveRequest: "/leave/manage",
    LeaveConfiguration: "/leave/configuration",
    MyOvertimeRequest: "/overtime/my",
    ManageOvertimeRequest: "/overtime/manage",
    WorkforceAnalytics: "/analytics/workforce",
    CompetencyReport: "/competency/report",
    PerformanceTemplates: "/performance/templates",
    PerformanceCycles: "/performance/cycles",
    EvaluatorAssignments: "/performance/assignments",
    EvaluationList: "/performance/evaluations",
    PerformanceCriteria: "/performance/templates/:templateId/criteria",
    ManageSystemSettings: "/admin/system-settings",
}

export default URL
